# quiz2.py


# while loops, strings, lists, for loops
# We wrote a random_number function that returns 0, 1 or 2
# Write a while loop. In every iteration it should call the fight function
# with a number generated by random_number and a list of two players,
# that should do the following:
#   - print who is fighting
#   - if number is 0 or 1: 
#       - print who won
#       - return who won
#   - if number is 2: 
#       - print both unconscious
#       - return None
# The while loop should append the winners to a list if a player is returned
# The while loop should break the loop if None is returned
# After the loop, print each player name and how often they have won


## I AM NOT DONE

from random import randint

def random_number() -> int:
    return randint(0, 2)

def fight(number: int, players: list) -> str | None:
    return

players = ["Alex", "Sam"]

winners = []

while True:
    fight(random_number(), players)


print(players[0], players)
print(players[1], players)

